events {
    worker_connections 1024;
}

http {

    # Contenedor principal
    upstream media_service {
        server media-service:8000;
    }

    # Aplicaciones (Conexión contra el BFF)
    upstream app_bff_client1 {
        server bff-client1:3000; # Nombre del contenedor del BFF en la red de Docker
    }

    server {
        listen 80;
        server_name media.tudominio.com;

        location / {
            proxy_pass http://media_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name app1.tudominio.com;

        location / {
            proxy_pass http://app_bff_client1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
