version: '3.8'

# Red compartida por la que se comunicarán los contenedores en el Servidor
networks:
  core-network:
    name: core-network
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  valkey_data:

services:
  # 1. Base de Datos Relacional
  postgres:
    image: postgres:16-alpine
    container_name: core-postgres
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: admin
      POSTGRES_PASS: database_password # TODO: Contraseña real, añadir archivo a .gitignore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core-network

  # 2. Base de Datos No Relacional (Documental)
  mongodb:
    image: mongo:7.0
    container_name: core-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - core-network

  # 3. Caché y Key-Value Store (Valkey, compatible con Redis)
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: core-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - core-network

  # 4. Bus de eventos (Mensajería)
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: core-rabbitmq
    ports:
      - "5672:5672" # Puerto de mensajería AMQP (Advanced Message Queuing Protocol)
      - "15672:15672" # Puerto de Administración Web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - core-network

  # 5. Microservicio de Procesamiento de imágenes (1 por servidor, poco frecuente)
  media_service:
    build:
      context: ./services/media_service
    container_name: core-media_service
    networks:
      - core-network

  # 6. Enrutador Primario (DNS)
  nginx-router:
    image: nginx:alpine
    container_name: core-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - media_service
    networks:
      - core-network
