spring.application.name=users_service

# Servicio OAuth de Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#Servicio OAuth de Microsoft
spring.security.oauth2.client.registration.azure.client-id=${MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/common/v2.0

# Hibernate
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# JWT y KeyStore (Archivo KeyStore PKCS12 con el par de claves RSA -privada/pública)
app.security.jwt.keystore-location=classpath:cert/auth-keystore.p12
app.security.jwt.keystore-password=${KEYSTORE_PASSWORD}
app.security.jwt.key-alias=${KEYSTORE_KEY_ALIAS}
app.security.jwt.key-password=${KEYSTORE_KEY_PASSWORD}
app.security.jwt.expiration-ms=86400000

# ==========================================
# Actuator / Endpoints de Salud
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
